"use client";

import { useState } from "react";

interface EvidenceBadgeProps {
    agentCount?: number;
    crossValidated?: boolean;
    deterministicScoring?: boolean;
}

export default function EvidenceBadge({
    agentCount = 8,
    crossValidated = true,
    deterministicScoring = true,
}: EvidenceBadgeProps) {
    const [isOpen, setIsOpen] = useState(false);

    return (
        <div className="relative inline-block z-40">
            {/* Collapsed Pill */}
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/30 hover:bg-blue-500/20 transition-colors text-blue-400 text-xs font-semibold select-none"
            >
                Evidence ✓
            </button>

            {/* Expanded Popover */}
            {isOpen && (
                <div className="absolute top-full mt-2 right-0 w-64 bg-[#0b101e] border border-war-border p-4 rounded-xl shadow-2xl fade-in z-50">
                    <div className="flex justify-between items-center mb-3">
                        <h4 className="text-xs uppercase tracking-wider text-war-text-dim font-bold">
                            Verification Details
                        </h4>
                        <button
                            className="text-war-text-dim hover:text-white"
                            onClick={() => setIsOpen(false)}
                        >
                            ✕
                        </button>
                    </div>

                    <ul className="space-y-2 text-xs text-war-text">
                        <li className="flex items-start gap-2">
                            <span className="text-blue-400 mt-0.5">▪</span>
                            <span>Generated by: <strong>{agentCount} AI agents</strong></span>
                        </li>
                        {crossValidated && (
                            <li className="flex items-start gap-2">
                                <span className="text-blue-400 mt-0.5">▪</span>
                                <span>Cross-validated (confidence adjusted)</span>
                            </li>
                        )}
                        {deterministicScoring && (
                            <li className="flex items-start gap-2">
                                <span className="text-blue-400 mt-0.5">▪</span>
                                <span>Deterministic risk scoring applied</span>
                            </li>
                        )}
                    </ul>
                </div>
            )}
        </div>
    );
}
